### ISSUE TITLE
Assignment4_MaskRCNN_test.py

### ISSUE THREAD

**Issue by lyf1212** [ateb14/Intro2CV#1]
为什么在test.py的第51行没有在pred_label==cls的限制条件下？也许应该加一个缩进？

**Comment by ChandlerWang14** [comment]
啊其实那一块确实之前写的有问题，昨天修改了忘记push上来了，是应该只在pred_label==cls下做的😂

**Comment by lyf1212** [comment]
👍

**Comment by lyf1212** [comment]
但貌似你的代码中是在gt['labels'][0] == cls下做的？我不清楚你pull的情况，我们的思路应该是相同的，所以问题不大~
